name: Python package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: Build for ${{ matrix.os }} with Python 3.12
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Sync dependencies
        run: |
          uv sync --all-extras --dev

      - name: Run unit tests
        run: |
          uv run pytest

      - name: Verify that we can build the package
        run: |
          uv build

  lint:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    name: Linting build
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Sync dependencies
        run: |
          uv sync --all-extras --dev

      - name: Check style against standards using ruff
        run: |
          uv run ruff check .
